version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: cta_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cta_db
    ports:
      - "5432:5432"
    volumes:
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    container_name: cta_backend
    restart: always
    depends_on:
      - postgres
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    command: >
      sh -c "alembic upgrade head &&
             uvicorn main:app --host 0.0.0.0 --port 8000"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: cta_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
