"""add_payment_payout_tables

Revision ID: dc2117b54c55
Revises: cd9ba35470b6
Create Date: 2025-09-20 08:33:44.733897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dc2117b54c55'
down_revision: Union[str, Sequence[str], None] = 'cd9ba35470b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usermaster', sa.Column('vpa_id', sa.String(length=100), nullable=True))
    op.add_column('usermaster', sa.Column('onboarding_status', sa.String(length=20), server_default='pending', nullable=True))
    op.add_column('usermaster', sa.Column('rejection_reason', sa.Text(), nullable=True))
    
    op.create_table('user_payment_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('razorpay_contact_id', sa.String(length=100), nullable=True),
    sa.Column('razorpay_fund_account_id', sa.String(length=100), nullable=True),
    sa.Column('verification_status', sa.String(length=20), server_default='pending', nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['usermaster.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    
    op.create_table('payouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='INR', nullable=True),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=True),
    sa.Column('razorpay_payout_id', sa.String(length=100), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['usermaster.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.create_index(op.f('ix_payouts_id'), 'payouts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payouts_id'), table_name='payouts')
    op.drop_table('payouts')
    op.drop_table('user_payment_profiles')
    op.drop_column('usermaster', 'rejection_reason')
    op.drop_column('usermaster', 'onboarding_status')
    op.drop_column('usermaster', 'vpa_id')
    # ### end Alembic commands ###
