"""create_assets_table

Revision ID: 15ac74098596
Revises: bebcb1805f10
Create Date: 2025-09-10 05:24:36.001014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15ac74098596'
down_revision: Union[str, Sequence[str], None] = 'bebcb1805f10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
        sa.Column('asset_id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('asset_name', sa.String(length=150), nullable=False),
        sa.Column('asset_type', sa.String(length=50), nullable=False),
        sa.Column('asset_serial_number', sa.String(length=100), nullable=True),
        sa.Column('asset_model', sa.String(length=100), nullable=True),
        sa.Column('asset_specifications', sa.Text(), nullable=True),
        sa.Column('assigned_to', sa.Integer(), nullable=True),
        sa.Column('assigned_location', sa.String(length=150), nullable=True),
        sa.Column('allocated_on', sa.DateTime(), nullable=True),
        sa.Column('status', sa.String(length=20), server_default='available', nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.Column('created_by', sa.Integer(), nullable=True),
        sa.Column('updated_by', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['assigned_to'], ['usermaster.user_id'], ),
        sa.PrimaryKeyConstraint('asset_id')
    )
    
    # Create indexes
    op.create_index(op.f('ix_assets_asset_id'), 'assets', ['asset_id'], unique=False)
    op.create_index(op.f('ix_assets_asset_serial_number'), 'assets', ['asset_serial_number'], unique=True)
    op.create_index(op.f('ix_assets_asset_type'), 'assets', ['asset_type'], unique=False)
    op.create_index(op.f('ix_assets_assigned_to'), 'assets', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_assets_status'), 'assets', ['status'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assets_status'), table_name='assets')
    op.drop_index(op.f('ix_assets_assigned_to'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset_type'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset_serial_number'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset_id'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
