"""Models added v1

Revision ID: 7156da120d72
Revises: 595d2f8b2f18
Create Date: 2025-08-28 05:50:59.317835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7156da120d72'
down_revision: Union[str, Sequence[str], None] = '595d2f8b2f18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entitymaster',
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_name', sa.String(length=150), nullable=True),
    sa.Column('customer_name', sa.String(length=150), nullable=True),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('segment', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('contact_number', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('geo_lat', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('geo_long', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_index(op.f('ix_entitymaster_entity_id'), 'entitymaster', ['entity_id'], unique=False)
    op.create_table('productmaster',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('sl_no', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('cell', sa.String(length=50), nullable=True),
    sa.Column('vehicle_application', sa.String(length=150), nullable=True),
    sa.Column('segment_product', sa.String(length=100), nullable=True),
    sa.Column('product_name', sa.String(length=150), nullable=True),
    sa.Column('part_no', sa.String(length=50), nullable=True),
    sa.Column('grade', sa.String(length=50), nullable=True),
    sa.Column('size', sa.String(length=50), nullable=True),
    sa.Column('net_qty_inner', sa.Integer(), nullable=True),
    sa.Column('net_qty_master', sa.Integer(), nullable=True),
    sa.Column('size1', sa.String(length=50), nullable=True),
    sa.Column('mechanic_coupon_inner', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('mrp_inner', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('mrp_master', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('barcode', sa.String(length=50), nullable=True),
    sa.Column('prd_code', sa.String(length=50), nullable=True),
    sa.Column('padi_cell', sa.String(length=50), nullable=True),
    sa.Column('tskp1_cell', sa.String(length=50), nullable=True),
    sa.Column('tskp2_cell', sa.String(length=50), nullable=True),
    sa.Column('lbl_status', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_index(op.f('ix_productmaster_product_id'), 'productmaster', ['product_id'], unique=False)
    op.create_table('usermaster',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('t_no', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('hq', sa.String(length=150), nullable=True),
    sa.Column('responsibility', sa.String(length=150), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('reports_to', sa.Integer(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('mobile', sa.String(length=15), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_usermaster_email'), 'usermaster', ['email'], unique=True)
    op.create_index(op.f('ix_usermaster_mobile'), 'usermaster', ['mobile'], unique=True)
    op.create_index(op.f('ix_usermaster_user_id'), 'usermaster', ['user_id'], unique=False)
    op.create_table('auditlog',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=True),
    sa.Column('entity_name', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['usermaster.user_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_auditlog_log_id'), 'auditlog', ['log_id'], unique=False)
    op.create_table('couponbatch',
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('coupon_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('qr_prefix', sa.String(length=20), nullable=True),
    sa.Column('printed_by', sa.Integer(), nullable=True),
    sa.Column('printed_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['productmaster.product_id'], ),
    sa.PrimaryKeyConstraint('batch_id')
    )
    op.create_index(op.f('ix_couponbatch_batch_id'), 'couponbatch', ['batch_id'], unique=False)
    op.create_table('loginsession',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('login_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('logout_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('device_info', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['usermaster.user_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_loginsession_session_id'), 'loginsession', ['session_id'], unique=False)
    op.create_table('scansession',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('msr_id', sa.Integer(), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('location_lat', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('location_long', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('total_coupons', sa.Integer(), nullable=True),
    sa.Column('valid_coupons', sa.Integer(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('payment_screenshot_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entitymaster.entity_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_scansession_session_id'), 'scansession', ['session_id'], unique=False)
    op.create_table('approvallog',
    sa.Column('approval_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('approver_id', sa.Integer(), nullable=True),
    sa.Column('approver_role', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['scansession.session_id'], ),
    sa.PrimaryKeyConstraint('approval_id')
    )
    op.create_index(op.f('ix_approvallog_approval_id'), 'approvallog', ['approval_id'], unique=False)
    op.create_table('couponlabel',
    sa.Column('coupon_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('qr_code', sa.String(length=255), nullable=True),
    sa.Column('unique_num', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('scanned_by', sa.Integer(), nullable=True),
    sa.Column('scanned_on', sa.TIMESTAMP(), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['couponbatch.batch_id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entitymaster.entity_id'], ),
    sa.PrimaryKeyConstraint('coupon_id')
    )
    op.create_index(op.f('ix_couponlabel_coupon_id'), 'couponlabel', ['coupon_id'], unique=False)
    op.create_table('payment_transaction',
    sa.Column('txn_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('payee_id', sa.Integer(), nullable=True),
    sa.Column('payee_role', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('txn_number', sa.String(length=50), nullable=True),
    sa.Column('txn_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['scansession.session_id'], ),
    sa.PrimaryKeyConstraint('txn_id')
    )
    op.create_index(op.f('ix_payment_transaction_txn_id'), 'payment_transaction', ['txn_id'], unique=False)
    op.create_table('query_thread',
    sa.Column('query_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('raised_by', sa.Integer(), nullable=True),
    sa.Column('responded_by', sa.Integer(), nullable=True),
    sa.Column('query_text', sa.Text(), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['scansession.session_id'], ),
    sa.PrimaryKeyConstraint('query_id')
    )
    op.create_index(op.f('ix_query_thread_query_id'), 'query_thread', ['query_id'], unique=False)
    op.create_table('scansessiondetails',
    sa.Column('detail_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('coupon_id', sa.Integer(), nullable=True),
    sa.Column('validation_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['coupon_id'], ['couponlabel.coupon_id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['scansession.session_id'], ),
    sa.PrimaryKeyConstraint('detail_id')
    )
    op.create_index(op.f('ix_scansessiondetails_detail_id'), 'scansessiondetails', ['detail_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scansessiondetails_detail_id'), table_name='scansessiondetails')
    op.drop_table('scansessiondetails')
    op.drop_index(op.f('ix_query_thread_query_id'), table_name='query_thread')
    op.drop_table('query_thread')
    op.drop_index(op.f('ix_payment_transaction_txn_id'), table_name='payment_transaction')
    op.drop_table('payment_transaction')
    op.drop_index(op.f('ix_couponlabel_coupon_id'), table_name='couponlabel')
    op.drop_table('couponlabel')
    op.drop_index(op.f('ix_approvallog_approval_id'), table_name='approvallog')
    op.drop_table('approvallog')
    op.drop_index(op.f('ix_scansession_session_id'), table_name='scansession')
    op.drop_table('scansession')
    op.drop_index(op.f('ix_loginsession_session_id'), table_name='loginsession')
    op.drop_table('loginsession')
    op.drop_index(op.f('ix_couponbatch_batch_id'), table_name='couponbatch')
    op.drop_table('couponbatch')
    op.drop_index(op.f('ix_auditlog_log_id'), table_name='auditlog')
    op.drop_table('auditlog')
    op.drop_index(op.f('ix_usermaster_user_id'), table_name='usermaster')
    op.drop_index(op.f('ix_usermaster_mobile'), table_name='usermaster')
    op.drop_index(op.f('ix_usermaster_email'), table_name='usermaster')
    op.drop_table('usermaster')
    op.drop_index(op.f('ix_productmaster_product_id'), table_name='productmaster')
    op.drop_table('productmaster')
    op.drop_index(op.f('ix_entitymaster_entity_id'), table_name='entitymaster')
    op.drop_table('entitymaster')
    # ### end Alembic commands ###
