"""add_address_fields_and_remove_address_column

Revision ID: 990ec5a9a727
Revises: bebcb1805f10
Create Date: 2025-09-10 16:15:47.100438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '990ec5a9a727'
down_revision: Union[str, Sequence[str], None] = 'bebcb1805f10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add new columns
    op.add_column('usermaster', sa.Column('address_line1', sa.Text(), nullable=False))
    op.add_column('usermaster', sa.Column('address_line2', sa.Text(), nullable=False))
    op.add_column('usermaster', sa.Column('state', sa.Text(), nullable=False))
    op.add_column('usermaster', sa.Column('district', sa.Text(), nullable=False))
    op.add_column('usermaster', sa.Column('pincode', sa.String(length=6), nullable=False))
    
    # Drop the old address column
    op.drop_column('usermaster', 'address')
    
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add back the old address column
    op.add_column('usermaster', sa.Column('address', sa.Text(), nullable=False))
    
    # Drop the new columns
    op.drop_column('usermaster', 'address_line1')
    op.drop_column('usermaster', 'address_line2')
    op.drop_column('usermaster', 'state')
    op.drop_column('usermaster', 'district')
    op.drop_column('usermaster', 'pincode')