"""add_mechanic_fields_to_draft_sessions

Revision ID: bebcb1805f10
Revises: d76f98b61325
Create Date: 2025-09-03 10:59:40.343090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import func


# revision identifiers, used by Alembic.
revision: str = 'bebcb1805f10'
down_revision: Union[str, Sequence[str], None] = 'd76f98b61325'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # First create the table if it doesn't exist
    op.create_table('draft_sessions',
        sa.Column('draft_session_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('scanned_coupons', sa.JSON(), nullable=True, server_default='[]'),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=func.now(), nullable=True),
        sa.Column('updated_at', sa.TIMESTAMP(), server_default=func.now(), onupdate=func.now(), nullable=True),
        sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True),
        sa.PrimaryKeyConstraint('draft_session_id')
    )
    op.create_index(op.f('ix_draft_sessions_draft_session_id'), 'draft_sessions', ['draft_session_id'], unique=False)
    
    # Then add the new columns
    op.add_column('draft_sessions', sa.Column('mechanic_id', sa.Integer(), nullable=True))
    op.add_column('draft_sessions', sa.Column('mechanic_address', sa.String(), nullable=True))
    
    # For existing records (though there shouldn't be any), set default values
    op.execute("UPDATE draft_sessions SET mechanic_id = -1, mechanic_address = 'Unknown'")
    
    # Now alter the column to be NOT NULL
    op.alter_column('draft_sessions', 'mechanic_id', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('draft_sessions', 'mechanic_address')
    op.drop_column('draft_sessions', 'mechanic_id')
    op.drop_index(op.f('ix_draft_sessions_draft_session_id'), table_name='draft_sessions')
    op.drop_table('draft_sessions')
    # ### end Alembic commands ###