"""Add is_verified column to LoginSession

Revision ID: d3e3b768f0ac
Revises: cf4e68394a17
Create Date: 2025-09-03 05:29:20.344416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3e3b768f0ac'
down_revision: Union[str, Sequence[str], None] = 'cf4e68394a17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loginsession', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.alter_column('usermaster', 't_no',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usermaster', 't_no',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('loginsession', 'is_verified')
    # ### end Alembic commands ###
