name: Build and Push Frontend Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - uses: actions/checkout@v3

      # 2. Set up Docker Buildx
      - uses: docker/setup-buildx-action@v3

      # 3. Log in to GitHub Container Registry (GHCR)
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: arunautogit   # lowercase
          password: ${{ secrets.GITHUB_TOKEN }}

      # 4. Build Docker image
      - run: docker build -t ghcr.io/arunautogit/requireddelete/frontend:latest .

      # 5. Push Docker image
      - run: docker push ghcr.io/arunautogit/requireddelete/frontend:latest
