name: Build and Push Docker Images

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2️⃣ Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3️⃣ Log in to GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: arunautogit    # must be lowercase
          password: ${{ secrets.GITHUB_TOKEN }}

      # 4️⃣ Build and push Frontend Docker image
      - name: Build Frontend Docker image
        run: |
          docker build -t ghcr.io/arunautogit/requireddelete/frontend:latest ./frontend
          docker push ghcr.io/arunautogit/requireddelete/frontend:latest

      # 5️⃣ Build and push Backend Docker image
      - name: Build Backend Docker image
        run: |
          docker build -t ghcr.io/arunautogit/requireddelete/backend:latest ./backend
          docker push ghcr.io/arunautogit/requireddelete/backend:latest
